// js/locations.js
// Built-in preset list of Queensland coastal locations with official Maritime
// Safety Queensland (MSQ) tide-gauge stations (data.qld.gov.au). Each preset's
// tideStationId matches a bundled data/tides/<tideStationId>-<year>.csv file
// (official predicted high/low data). Users can still type any custom name +
// lat/lon; locations without a bundled CSV fall back to the WorldTides API.

window.LOCATION_PRESETS = [
  {
    id: "waddy-point",
    name: "Waddy Point, K'gari (Fraser Island), Queensland, Australia",
    region: "Fraser Coast",
    lat: -24.9675,
    lon: 153.3369,
    timezone: "Australia/Brisbane",
    // matches data/tides/<tideStationId>-<year>.csv (official MSQ/BOM predictions)
    tideStationId: "waddy-point-kgari",
  },
  {
    id: "thursday-island",
    name: "Thursday Island, Queensland, Australia",
    region: "Torres Strait",
    lat: -10.5833,
    lon: 142.2167,
    timezone: "Australia/Brisbane",
    tideStationId: "thursday-island",
  },
  {
    id: "cooktown",
    name: "Cooktown, Queensland, Australia",
    region: "Cape York",
    lat: -15.45,
    lon: 145.2333,
    timezone: "Australia/Brisbane",
    tideStationId: "cooktown",
  },
  {
    id: "cape-flattery",
    name: "Cape Flattery, Queensland, Australia",
    region: "Cape York",
    lat: -14.95,
    lon: 145.3,
    timezone: "Australia/Brisbane",
    tideStationId: "cape-flattery",
  },
  {
    id: "lizard-island",
    name: "Lizard Island, Queensland, Australia",
    region: "Cape York",
    lat: -14.6667,
    lon: 145.4333,
    timezone: "Australia/Brisbane",
    tideStationId: "lizard-island",
  },
  {
    id: "weipa",
    name: "Weipa, Queensland, Australia",
    region: "Cape York",
    lat: -12.6667,
    lon: 141.85,
    timezone: "Australia/Brisbane",
    tideStationId: "weipa",
  },
  {
    id: "karumba",
    name: "Karumba, Queensland, Australia",
    region: "Gulf of Carpentaria",
    lat: -17.4833,
    lon: 140.8333,
    timezone: "Australia/Brisbane",
    tideStationId: "karumba",
  },
  {
    id: "clump-point",
    name: "Clump Point, Mission Beach, Queensland, Australia",
    region: "Far North Queensland",
    lat: -17.85,
    lon: 146.1,
    timezone: "Australia/Brisbane",
    tideStationId: "clump-point",
  },
  {
    id: "mourilyan",
    name: "Mourilyan Harbour, Queensland, Australia",
    region: "Far North Queensland",
    lat: -17.5833,
    lon: 146.1167,
    timezone: "Australia/Brisbane",
    tideStationId: "mourilyan",
  },
  {
    id: "cairns",
    name: "Cairns, Queensland, Australia",
    region: "Far North Queensland",
    lat: -16.9167,
    lon: 145.7667,
    timezone: "Australia/Brisbane",
    tideStationId: "cairns",
  },
  {
    id: "port-douglas",
    name: "Port Douglas, Queensland, Australia",
    region: "Far North Queensland",
    lat: -16.4833,
    lon: 145.45,
    timezone: "Australia/Brisbane",
    tideStationId: "port-douglas",
  },
  {
    id: "mossman",
    name: "Mossman, Queensland, Australia",
    region: "Far North Queensland",
    lat: -16.4167,
    lon: 145.4,
    timezone: "Australia/Brisbane",
    tideStationId: "mossman",
  },
  {
    id: "townsville",
    name: "Townsville, Queensland, Australia",
    region: "Townsville/Cardwell",
    lat: -19.2333,
    lon: 146.8333,
    timezone: "Australia/Brisbane",
    tideStationId: "townsville",
  },
  {
    id: "lucinda",
    name: "Lucinda, Queensland, Australia",
    region: "Townsville/Cardwell",
    lat: -18.5167,
    lon: 146.3833,
    timezone: "Australia/Brisbane",
    tideStationId: "lucinda",
  },
  {
    id: "cardwell",
    name: "Cardwell, Queensland, Australia",
    region: "Townsville/Cardwell",
    lat: -18.25,
    lon: 146.0167,
    timezone: "Australia/Brisbane",
    tideStationId: "cardwell",
  },
  {
    id: "hay-point",
    name: "Hay Point, Queensland, Australia",
    region: "Mackay/Whitsundays",
    lat: -21.2667,
    lon: 149.3,
    timezone: "Australia/Brisbane",
    tideStationId: "hay-point",
  },
  {
    id: "mackay",
    name: "Mackay, Queensland, Australia",
    region: "Mackay/Whitsundays",
    lat: -21.1,
    lon: 149.2167,
    timezone: "Australia/Brisbane",
    tideStationId: "mackay",
  },
  {
    id: "shute-harbour",
    name: "Shute Harbour, Whitsundays, Queensland, Australia",
    region: "Mackay/Whitsundays",
    lat: -20.2833,
    lon: 148.7833,
    timezone: "Australia/Brisbane",
    tideStationId: "shute-harbour",
  },
  {
    id: "bowen",
    name: "Bowen, Queensland, Australia",
    region: "Mackay/Whitsundays",
    lat: -20.0167,
    lon: 148.25,
    timezone: "Australia/Brisbane",
    tideStationId: "bowen",
  },
  {
    id: "abbot-point",
    name: "Abbot Point, Queensland, Australia",
    region: "Mackay/Whitsundays",
    lat: -19.85,
    lon: 148.0833,
    timezone: "Australia/Brisbane",
    tideStationId: "abbot-point",
  },
  {
    id: "gladstone-auckland-point",
    name: "Gladstone, Queensland, Australia",
    region: "Capricorn Coast",
    lat: -23.8167,
    lon: 151.25,
    timezone: "Australia/Brisbane",
    tideStationId: "gladstone-auckland-point",
  },
  {
    id: "port-alma",
    name: "Port Alma, Queensland, Australia",
    region: "Capricorn Coast",
    lat: -23.5833,
    lon: 150.85,
    timezone: "Australia/Brisbane",
    tideStationId: "port-alma",
  },
  {
    id: "rockhampton",
    name: "Rockhampton, Queensland, Australia",
    region: "Capricorn Coast",
    lat: -23.3667,
    lon: 150.5167,
    timezone: "Australia/Brisbane",
    tideStationId: "rockhampton",
  },
  {
    id: "rosslyn-bay",
    name: "Rosslyn Bay, Queensland, Australia",
    region: "Capricorn Coast",
    lat: -23.15,
    lon: 150.7833,
    timezone: "Australia/Brisbane",
    tideStationId: "rosslyn-bay",
  },
  {
    id: "urangan",
    name: "Urangan, Hervey Bay, Queensland, Australia",
    region: "Fraser Coast",
    lat: -25.2833,
    lon: 152.9,
    timezone: "Australia/Brisbane",
    tideStationId: "urangan",
  },
  {
    id: "bundaberg",
    name: "Bundaberg (Burnett Heads), Queensland, Australia",
    region: "Fraser Coast",
    lat: -24.7667,
    lon: 152.3667,
    timezone: "Australia/Brisbane",
    tideStationId: "bundaberg",
  },
  {
    id: "burnett-heads",
    name: "Burnett Heads, Queensland, Australia",
    region: "Fraser Coast",
    lat: -24.75,
    lon: 152.4,
    timezone: "Australia/Brisbane",
    tideStationId: "burnett-heads",
  },
  {
    id: "mooloolaba",
    name: "Mooloolaba, Queensland, Australia",
    region: "Sunshine Coast",
    lat: -26.6833,
    lon: 153.1333,
    timezone: "Australia/Brisbane",
    tideStationId: "mooloolaba",
  },
  {
    id: "noosa-head",
    name: "Noosa Head, Queensland, Australia",
    region: "Sunshine Coast",
    lat: -26.3833,
    lon: 153.1,
    timezone: "Australia/Brisbane",
    tideStationId: "noosa-head",
  },
  {
    id: "tin-can-bay-snapper-creek",
    name: "Tin Can Bay, Queensland, Australia",
    region: "Sunshine Coast",
    lat: -25.9,
    lon: 153.0,
    timezone: "Australia/Brisbane",
    tideStationId: "tin-can-bay-snapper-creek",
  },
  {
    id: "southport",
    name: "Southport, Queensland, Australia",
    region: "South East Queensland",
    lat: -27.9667,
    lon: 153.4167,
    timezone: "Australia/Brisbane",
    tideStationId: "southport",
  },
  {
    id: "gold-coast-seaway",
    name: "Gold Coast Seaway, Queensland, Australia",
    region: "South East Queensland",
    lat: -27.9333,
    lon: 153.4167,
    timezone: "Australia/Brisbane",
    tideStationId: "gold-coast-seaway",
  },
  {
    id: "brisbane-bar",
    name: "Brisbane Bar, Queensland, Australia",
    region: "South East Queensland",
    lat: -27.4,
    lon: 153.15,
    timezone: "Australia/Brisbane",
    tideStationId: "brisbane-bar",
  },
  {
    id: "shorncliffe",
    name: "Shorncliffe, Queensland, Australia",
    region: "South East Queensland",
    lat: -27.3167,
    lon: 153.0833,
    timezone: "Australia/Brisbane",
    tideStationId: "shorncliffe",
  },
  {
    id: "scarborough",
    name: "Scarborough, Queensland, Australia",
    region: "South East Queensland",
    lat: -27.1833,
    lon: 153.1,
    timezone: "Australia/Brisbane",
    tideStationId: "scarborough",
  },
  {
    id: "tangalooma",
    name: "Tangalooma, Moreton Island, Queensland, Australia",
    region: "South East Queensland",
    lat: -27.1667,
    lon: 153.3667,
    timezone: "Australia/Brisbane",
    tideStationId: "tangalooma",
  },
];
